<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    
    <!-- RimWorld packages -->
    <ItemGroup>
        <PackageVersion Include="Lib.Harmony" Version="2.4.1" />
        <PackageVersion Include="Krafs.Rimworld.Ref" Version="1.6.4566" />
    </ItemGroup>
    
    <!-- Scripting packages -->
    <ItemGroup>
        <PackageVersion Include="MoonSharp" Version="2.0.0" />
    </ItemGroup>
</Project>