<Project Sdk="Microsoft.NET.Sdk">
    <!-- Package references -->
    <ItemGroup>
        <PackageReference Include="MoonSharp"/>
        <PackageReference Include="Krafs.Rimworld.Ref"/>
        <PackageReference Include="Lib.Harmony" ExcludeAssets="runtime"/>
    </ItemGroup>
    
    <!-- Local references -->
    <ItemGroup>
        <Reference Include="ToolkitCore">
            <HintPath>$(ToolkitCoreDir)\v1.6\Assemblies\ToolkitCore.dll</HintPath>
        </Reference>
        <Reference Include="TwitchLib.Client">
            <HintPath>$(ToolkitCoreDir)\Assemblies\TwitchLib.Client.dll</HintPath>
        </Reference>
        <Reference Include="TwitchLib.Client.Enums">
            <HintPath>$(ToolkitCoreDir)\Assemblies\TwitchLib.Client.Enums.dll</HintPath>
        </Reference>
        <Reference Include="TwitchLib.Client.Models">
            <HintPath>$(ToolkitCoreDir)\Assemblies\TwitchLib.Client.Models.dll</HintPath>
        </Reference>
        <Reference Include="TwitchLib.Communication">
            <HintPath>$(ToolkitCoreDir)\Assemblies\TwitchLib.Communication.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
